# Copyright 2026 Windweaver Customizations
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import api, fields, models
from odoo.tools import config


class ProjectProject(models.Model):
    _inherit = "project.project"

    # This intentionally does not use `_inherit = ["project.project", "dms.field.mixin"]`.
    # With project.project on Odoo 18 that pattern can make the registry treat this as
    # a separate ProjectProject model extension and collide with existing many2many
    # fields such as favorite_user_ids.  Instead, we copy the small dms.field.mixin
    # behavior onto project.project directly.
    dms_directory_ids = fields.One2many(
        "dms.directory",
        "res_id",
        string="DMS Directories",
        domain=lambda self: [
            ("res_model", "=", self._name),
            ("storage_id.save_type", "!=", "attachment"),
        ],
        auto_join=True,
    )

    def web_save(self, vals, specification, next_id=None):
        """Avoid dms.directory access errors when the field is empty/unavailable.

        This mirrors OCA dms_field's mixin behavior while avoiding multi-inherit
        registry issues on project.project.
        """
        f_name = "dms_directory_ids"
        if f_name not in vals and f_name in specification and not self[f_name]:
            del specification[f_name]
        return super().web_save(vals, specification, next_id)

    @api.model
    def models_to_track_dms_field_template(self):
        return self.env["dms.field.template"].sudo().search([]).mapped("model_id.model")

    @api.model_create_multi
    def create(self, vals_list):
        result = super().create(vals_list)
        test_condition = not config["test_enable"] or self.env.context.get("test_dms_field")
        if (
            test_condition
            and not self.env.context.get("skip_track_dms_field_template")
            and self._name in self.models_to_track_dms_field_template()
        ):
            template = self.env["dms.field.template"].with_context(res_model=self._name)
            for item in result:
                template.with_context(res_id=item.id).create_dms_directory()
        return result

    def write(self, vals):
        res = super().write(vals)
        # Apply sudo() in case the user does not have access to the directory.
        for item in self.sudo().filtered("dms_directory_ids"):
            if "user_id" in vals:
                template = self.env["dms.field.template"]._get_template_from_model(item._name)
                if template:
                    template.sudo()._get_autogenerated_group(item)
        return res

    def unlink(self):
        # Apply sudo() in case the user does not have access to the directory.
        for record in self.sudo().filtered("dms_directory_ids"):
            group = self.env["dms.access.group"].sudo()._get_item_from_dms_field_ref(record)
            record.sudo().dms_directory_ids.unlink()
            group.unlink()
        return super().unlink()
